"""
Company Server Clone Provisioner — Kurukshetra Phase 2 Demo.
Creates a sanitized, company-branded honeypot clone profile without touching real production.
"""

import json
import re
import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, asdict


# Patterns stripped during "sanitization" (simulated PII/secret scrub)
_SANITIZE_PATTERNS = [
    (re.compile(r"(?i)(password|passwd|secret|api_key|token)\s*[=:]\s*\S+"), r"\1=***REDACTED***"),
    (re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"), "***@***.***"),
    (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "***-**-****"),
    (re.compile(r"AKIA[0-9A-Z]{16}"), "AKIA***REDACTED***"),
]


@dataclass
class CloneProfile:
    clone_id: str
    company_name: str
    domain: str
    hostname: str
    web_title: str
    services: List[str]
    decoy_endpoints: List[str]
    sanitized: bool
    created_at: str
    backend_url: str
    status: str = "ACTIVE"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class CloneProvisioner:
    """Provisions a company-branded honeypot clone (sanitized mirror for deception)."""

    PROFILES_DIR = Path("clone_profiles")

    def __init__(self, profiles_dir: Optional[Path] = None):
        self.profiles_dir = profiles_dir or self.PROFILES_DIR
        self.profiles_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _slug(name: str) -> str:
        return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:32]

    @staticmethod
    def sanitize_text(text: str) -> str:
        """Remove PII/secrets from any imported config snippet."""
        out = text
        for pattern, repl in _SANITIZE_PATTERNS:
            out = pattern.sub(repl, out)
        return out

    def provision(
        self,
        company_name: str,
        domain: str,
        services: Optional[List[str]] = None,
        backend_url: str = "https://kurukshetra-backend.onrender.com",
        raw_config_snippet: Optional[str] = None,
    ) -> CloneProfile:
        """
        Create a new company clone profile:
        1. Generate branded hostname & portal title
        2. Sanitize any imported config
        3. Persist profile + .env overrides for honeypot
        """
        slug = self._slug(company_name)
        clone_id = f"CLONE-{slug}-{hashlib.md5(company_name.encode()).hexdigest()[:6].upper()}"
        hostname = f"{slug}-prod-01"
        web_title = f"{company_name} — Internal Enterprise Portal"
        svc = services or ["ssh", "web", "api"]

        decoys = [
            "/fake-credentials", "/fake-config", "/fake-users", "/fake-backup",
            "/admin", "/api/config", "/api/users", f"/{slug}/internal",
        ]

        sanitized = True
        if raw_config_snippet:
            self.sanitize_text(raw_config_snippet)

        profile = CloneProfile(
            clone_id=clone_id,
            company_name=company_name,
            domain=domain,
            hostname=hostname,
            web_title=web_title,
            services=svc,
            decoy_endpoints=decoys,
            sanitized=sanitized,
            created_at=datetime.now(timezone.utc).isoformat(),
            backend_url=backend_url.rstrip("/"),
            status="ACTIVE",
        )

        profile_path = self.profiles_dir / f"{slug}.json"
        profile_path.write_text(json.dumps(profile.to_dict(), indent=2), encoding="utf-8")

        self._write_env_overrides(profile, profile_path)
        self._write_active_pointer(slug)

        return profile

    def _write_active_pointer(self, slug: str) -> None:
        (self.profiles_dir / "active.json").write_text(
            json.dumps({"active_slug": slug, "updated_at": datetime.now(timezone.utc).isoformat()}),
            encoding="utf-8",
        )

    def _write_env_overrides(self, profile: CloneProfile, profile_path: Path) -> None:
        env_lines = [
            f"# Auto-generated by CloneProvisioner — {profile.clone_id}",
            f"HONEYPOT_HOSTNAME={profile.hostname}",
            f"WEB_TITLE={profile.web_title}",
            f"BACKEND_URL={profile.backend_url}",
            f"CLONE_PROFILE_PATH={profile_path.as_posix()}",
            f"CLONE_ID={profile.clone_id}",
            f"CLONE_COMPANY={profile.company_name}",
            f"CLONE_DOMAIN={profile.domain}",
        ]
        env_file = Path(".env.clone")
        env_file.write_text("\n".join(env_lines) + "\n", encoding="utf-8")

    def load_active_profile(self) -> Optional[CloneProfile]:
        pointer = self.profiles_dir / "active.json"
        if not pointer.exists():
            return None
        try:
            slug = json.loads(pointer.read_text(encoding="utf-8")).get("active_slug")
            path = self.profiles_dir / f"{slug}.json"
            if path.exists():
                data = json.loads(path.read_text(encoding="utf-8"))
                return CloneProfile(**data)
        except Exception:
            pass
        return None

    def list_profiles(self) -> List[Dict[str, Any]]:
        out = []
        for p in self.profiles_dir.glob("*.json"):
            if p.name == "active.json":
                continue
            try:
                out.append(json.loads(p.read_text(encoding="utf-8")))
            except Exception:
                pass
        return out

    def apply_to_settings(self) -> Optional[CloneProfile]:
        """Apply active clone profile to runtime settings (called on honeypot boot)."""
        profile = self.load_active_profile()
        if not profile:
            return None
        try:
            from honeypot.config.settings import settings
            settings.HONEYPOT_HOSTNAME = profile.hostname
            settings.WEB_TITLE = profile.web_title
            if profile.backend_url:
                settings.BACKEND_URL = profile.backend_url
        except Exception:
            pass
        return profile
